// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxdopRHtSdAiUIqeqH3cplwk0nNU-sedA',
    appId: '1:655802989961:web:b9012d50ceae1fa2adf558',
    messagingSenderId: '655802989961',
    projectId: 'unitool-565',
    authDomain: 'unitool-565.firebaseapp.com',
    storageBucket: 'unitool-565.appspot.com',
    measurementId: 'G-302NNLZCSV',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxdopRHtSdAiUIqeqH3cplwk0nNU-sedA',
    appId: '1:655802989961:web:3a76617d0ec3085fadf558',
    messagingSenderId: '655802989961',
    projectId: 'unitool-565',
    authDomain: 'unitool-565.firebaseapp.com',
    storageBucket: 'unitool-565.appspot.com',
    measurementId: 'G-WGT7MY1G3X',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWtnOResdYCO8UfH4t_brxfvwDIaR9dYA',
    appId: '1:655802989961:ios:83e08bdb6b2f5c93adf558',
    messagingSenderId: '655802989961',
    projectId: 'unitool-565',
    storageBucket: 'unitool-565.appspot.com',
    iosBundleId: 'com.example.unitool',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWtnOResdYCO8UfH4t_brxfvwDIaR9dYA',
    appId: '1:655802989961:ios:83e08bdb6b2f5c93adf558',
    messagingSenderId: '655802989961',
    projectId: 'unitool-565',
    storageBucket: 'unitool-565.appspot.com',
    iosBundleId: 'com.example.unitool',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsMkT2NHNtDlLQnDhK4YutKBh2Ybccd70',
    appId: '1:655802989961:android:320dca4ae2c12721adf558',
    messagingSenderId: '655802989961',
    projectId: 'unitool-565',
    storageBucket: 'unitool-565.appspot.com',
  );

}